name: Fly
description: Run a command in a fly vm as a buildkite step
author: https://github.com/jazzdan
requirements:
  - curl
  - fly
configuration:
  properties:
    image:
      type: string
    organization:
      type: string
    secrets:
      type: array
    env:
      type: object
    cpus:
      type: number
    memory:
      type: number
    storage:
      type: number
    matrix:
      type: array
  required:
    - image
    - organization
    - cpus
    - memory
  additionalProperties: false
